name: Release Drafter

template: |
  ## 🚀 New Features
  ${FEATURES}

  ## 🐛 Bug Fixes
  ${BUG_FIXES}

  ## 📦 Other Changes
  ${OTHER_CHANGES}

categories:
  - title: "Features"
    label: "feature"
  - title: "Bug Fixes"
    label: "bug"
  - title: "Other Changes"
    label: ""
