name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
version-resolver: increase-minor
template: |
  ## 🚀 New Features
  ${FEATURES}

  ## 🐛 Bug Fixes
  ${BUG_FIXES}

  ## 📦 Other Changes
  ${OTHER_CHANGES}
